### ISSUE TITLE
Support for frameworks other than express

### ISSUE THREAD

**Issue by cbebry** [techpines/bone.io#18]
I stumbled upon this framework, and it seems to fill a niche my team has been missing.

I've noticed that express seems to be the maine framework for this project, at least based on the available documentation. Does bone.io has support for switching out frameworks, or some sort of framework-agnostic approach of usage?

Thanks for creating bone.io. I look forward to seeing where this project goes, and being a user.

**Comment by techpines** [comment]
@cbebry Bone.io does not depend on Express.

I used Express in the examples just because it seems to be the most popular way that people are running their node webapps currently.  

There is an express middleware function that serves the browser code, `bone.io.js` for convenience, although this file is also in the root of the project:

``` js
app.use(bone.static());
```

And for convenience there is also `bone.io.middleware` function that hooks into the express sessions, because that seems to be something that people always have problems with when running socket.io.

So really there are only two minor convenience functions for express users, but there is no tight integration between the two libraries.

**Comment by cbebry** [comment]
Thanks for the quick reply! It does make sense. I managed to get around the static serving function with a simple reference into my local node_modules folder. I'm curious how I could use the session part without express.

**Comment by techpines** [comment]
There are a bunch of examples on the Internet of grabbing the cookie from the socket.io handshake and then figuring out the session id from the cookie.  Then you grab the session object using your session id.  You could use what I have as an example, but you'll need to customize for whatever framework you're using.

https://github.com/techpines/bone.io/blob/master/lib/node/middleware.coffee

Hope that helps.

**Comment by cbebry** [comment]
That link puts me towards the right direction. Thanks for pointing that out.
