### ISSUE TITLE
Route fires 2x

### ISSUE THREAD

**Issue by dsteinbach** [techpines/bone.io#23]
In this example, if you click link route will fire twice:

``` javascript
<a href="#search/ohhyea">search</a>
<script>
    bone.router({
        routes: {
            "search/:query": "find"
        },
        find: function(query) {
            alert(query);
        }
    });
    bone.router.start();
</script>
```

**Comment by techpines** [comment]
@offtopicguy I'm looking into this right now.

**Comment by techpines** [comment]
Found the bug and updated the version to `0.8.8`.

We have tests, but the test framework at the moment is based on zombie.js, which is cool because it's node-based, but it's just no as robust as I'd like.  

I think I'm going to switch over to a testing framework based on casper.js, and reallly flesh out a lot more tests in the next few weeks.

**Comment by dsteinbach** [comment]
Awesome thanks :+1:
